### ISSUE TITLE
git checkout 대신 git restore/switch 활용

### ISSUE THREAD

**Issue by copyrat90** [JBNU-JEduTools/osscourse#10]
[5. Git 초급.pptx](https://github.com/hyunchan-park/osscourse/blob/87425cda2ebfd876910c4e61e76e16096082cce0/Slides%202020/5.%20Git%20%EC%B4%88%EA%B8%89.pptx) 슬라이드 설명 중에
`git checkout` 대신에 `git restore` 와 `git switch` 를 쓰면 어떨까 합니다.

*참고 링크 : https://blog.outsider.ne.kr/1505*

`git checkout` 은 아래 2가지 기능을 합니다.
> 1. **Working Directory 의 변경 사항을 버리는 기능**
> 2. **다른 branch 로 전환하는 기능**

만일 `test` 라는 이름의 branch 와 파일이 동시에 존재한다면, 실수할 위험이 있습니다.
`--` 를 넣으면 파일에만 적용되고, 안 넣으면 branch 를 선호하긴 하지만, 헷갈립니다.

그래서 **1번 기능만을 하는 `git restore` 하고, 2번 기능만을 하는 `git switch` 를 쓰는게 어떨까 합니다.**

`git status` 에 안내되는 Working Directory 의 변경을 Index 로 덮어씌우는 방법 문구도
예전 버전은 `git checkout -- <file>...` 로 안내되고 있었지만,
현재는 아래와 같이 `git restore <file>...` 로 안내되고 있습니다.
```git
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   test.c
```

**Comment by copyrat90** [comment]
추가로 `git switch --detach <commit>` 을 쓰면 Detached HEAD 상태로 만들 수 있습니다.

**Comment by hyunchan-park** [comment]
아 고맙습니다. 제가 이런 변경 내용은 파악하지 못하고 있었습니다.
학생이 슬라이드의 해당 부분을 적절하게 수정해보시는건 어떠실까요?
메일로 알려주시기 바랍니다.
